### ISSUE TITLE
ДЗ на проверку (Спортмастер)

### ISSUE THREAD

**Issue by Sokolovskaia** [Sokolovskaia/sportmaster#1]
В задаче про Спортмастер, если введен непредусмотренный тип данных (например, введены не цифры, а текст) для переменных "сумма покупки" или "сумма предыдущих покупок". Какой должен быть результат, возвращаемый функцией:

1. Выдавать текст об ошибке (Но в таком случае мы получаем функцию, которая может возвращать разные типы данных, что не очень хорошо). Пока остановилась на этом варианте решения.

2. В случае ошибки считаем, что бонусы = 0

3. Или есть другое решение?

**Comment by coursar** [comment]
Никак не реагировать, это будет проверять тот, кто работает с интерфейсом. В противном случае вам в функции придётся проверять слишком много всего.
